encoding    : UTF-8
title       : YouTube Geofind
exclude     : [.idea]
author      : mattwright324
copyright   : © 2018 Matthew Wright
github      : https://github.com/mattwright324/
github_repo : https://github.com/mattwright324/youtube-geofind/
gh_pages    : https://mattwright324.github.io/youtube-geofind/